"""Init

Revision ID: f83f3793a753
Revises: 
Create Date: 2025-05-14 11:45:13.985405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83f3793a753'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=250), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('roi_x1', sa.Integer(), nullable=False),
    sa.Column('roi_y1', sa.Integer(), nullable=False),
    sa.Column('roi_x2', sa.Integer(), nullable=False),
    sa.Column('roi_y2', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_data')
    # ### end Alembic commands ###
